### ISSUE TITLE
Incorrect permissions on zync-que service

### ISSUE THREAD

**Issue by sedroche** [3scale/3scale-operator#192]
I have followed the [getting started guide](https://github.com/3scale/3scale-operator#getting-started) using the `quay.io/3scale/3scale-operator:latest` image.

The expected routes do no appear, just the `backend` route is created.

The `zync-que` logs have this error:
```bash
W, [2019-07-10T13:16:50.882844 #1]  WARN -- K8s::Transport<https://172.30.0.1:443>: GET /apis/apps.3scale.net/v1alpha1/namespaces/openshift-3scale/apimanagers/3scale => HTTP 403 Forbidden in 0.003s
D, [2019-07-10T13:16:50.882887 #1] DEBUG -- K8s::Transport<https://172.30.0.1:443>: Response: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"apimanagers.apps.3scale.net \"3scale\" is forbidden: User \"system:serviceaccount:openshift-3scale:zync-que-sa\" cannot get resource \"apimanagers\" in API group \"apps.3scale.net\" in the namespace \"openshift-3scale\"","reason":"Forbidden","details":{"name":"3scale","group":"apps.3scale.net","kind":"apimanagers"},"code":403}
```
and if I add permissions to the `zync-que-role` that allow access (before the services are ready) I do see the correct routes.
```yaml
  - verbs:
      - '*'
    apiGroups:
      - apps.3scale.net
    resources:
      - '*'
```

**Comment by miguelsorianod** [comment]
Hi John,

We have performed a change in the Zync code that removes that dependency on APIManager.

Assuming you are using master branch (development) we have rebuilt the Zync nightly image to include this new changes. If you recreate the APIManager it should work without having to add that permission into the zync-que-role.

Can you try it?

Thank you.

**Comment by sedroche** [comment]
@miguelsorianod You are correct. The routes are being created with the newer image. Thank you.
