### ISSUE TITLE
MySQL database schema for HA deployments not automatically created

### ISSUE THREAD

**Issue by obrienrobert** [3scale/3scale-operator#193]
**Description**

When deploying 3scale using the operators HA custom resource, an external MySQL database connection string must be provided, in the following format:

```mysql2://root:<password>@<host-name>:<port>/<database-name>```

**Request**

For external database sources, the database schema must be created manually before the operator is run. The host name must then be updated to include the newly created database name before the operator can be deployed.

Perhaps it might be possible for the 3scale operator to create the database schema automatically?

**Comment by eguzki** [comment]
This issue does not belong to the operator. The operator cannot be responsible of managing DB schemas and doing DDL operations. 

Open issue in https://github.com/3scale/porta/ if you find appropriate.
