### ISSUE TITLE
OpenShift 4.1.3 Operator Installation Failures

### ISSUE THREAD

**Issue by mrhillsman** [3scale/3scale-operator#202]
OpenShift 4.1.3 via OpenShift Installer running on AWS
6 node cluster - 3 master 3 worker
Kubernetes v1.13.4+

In file pkg/3scale/amp/component/system.go at line 907 there is a attempt to use ReadWriteMany for the system-storage PVC which the default StorageClass does not support; system-app pod fails but changing to ReadWriteOnce allows the pod to complete.

Backend pods fail (backend-cron|redis|worker) with error - "error: update acceptor rejected backend-worker-1: pods for rc '3scale-operator/backend-worker-1' took longer than 1200 seconds to become available".

**Comment by miguelsorianod** [comment]
Hi @mrhillsman,

ReadWriteMany storage for system-storage PVC is a requirement of 3scale when using PVC as System's FileStorage.

Does your cluster currently have PersistentVolumes (PVs) that support ReadWriteMany provisioned?

**Comment by mrhillsman** [comment]
@miguelsorianod i will add the storage required. in this case the documentation needs to be updated; under requirements is a good place. would you be able to make that update? i will see if the backend pods succeed after the additional storage.

**Comment by miguelsorianod** [comment]
Hi @mrhillsman ,

The official 3scale documentation already contains the prerequisites needed to deploy 3scale. In that documentation it is also explained how to deploy the product version of the operator there too (although the installation method for the product version will also change for 3scale 2.6 release):
https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.5/html/installing_3scale/onpremises-installation#prerequisites_2

However I guess it would be a good idea to document it too on the "upstream" version of the operator too as a prerequisite of the "APIManager" custom resource. Keep in mind that the officially supported version of 3scale is the productised version where you have the corresponding documentation that should be clear and contains stable images.

Also, as an alternative to PVC as system's fileStorage there's also the option of using S3 instead. There's documentation about it here: https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md#FileStorageSpec
