### ISSUE TITLE
Allow specifying s3 url in CR

### ISSUE THREAD

**Issue by philbrookes** [3scale/3scale-operator#249]
I wish to deploy 3scale using an s3 compliant API as the s3 storage solution. Unfortunately at the moment I cannot specify a URL for 3scale to use for s3: https://github.com/3scale/3scale-operator/blob/fcb4ad564782ecbf0687d6a253f829309d92319d/pkg/3scale/amp/component/s3.go#L171-L172

I would like to open a PR to add this functionality so that I can proceed with using minio as the backend. Is this something you would be likely to approve and merge?

**Comment by miguelsorianod** [comment]
Hi @philbrookes,

You should be able to define the bucket name and region in the .spec.system.fileStorage. amazonSimpleStorageService subsection of the APIManager. The reference can be hound here:
https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md#systems3spec

Would that work for you?

**Comment by philbrookes** [comment]
Apologies for the slow reply. I need to be able to specify the URL. This is so I can use another service (https://min.io/) with the same APIs as s3 as the s3 provider for 3scale.

**Comment by miguelsorianod** [comment]
Would it work by adding a parameter that would be the host name? (maybe also the scheme).
Then we would try to use the specified information.
I'm guessing the API needs an endpoint (hostname) and the information of the bucket (bucket name, credentials, region, ...)

This would not only require a change in the operator/templates itself but also on System/Porta component side which is the component that at the end is the one that potentially uses S3 as the FileStorage.

**Comment by philbrookes** [comment]
Yes, this sounds like what we need. If you could point me in the direction of where that change needs to be made in System/Porta, to help me get started, I would appreciate it!

**Comment by miguelsorianod** [comment]
Hi @philbrookes ,

I've opened an issue in our public Jira where we'll approach a solution to the request https://issues.jboss.org/browse/THREESCALE-3868

**Comment by philbrookes** [comment]
That's excellent news. Thanks @miguelsorianod !

**Comment by eguzki** [comment]
Implemented in https://github.com/3scale/3scale-operator/pull/302
