### ISSUE TITLE
Tenant controller cannot create/get admin access token from an existing tenant

### ISSUE THREAD

**Issue by eguzki** [3scale/3scale-operator#25]
As part of the tenant controller workflow, it needs to create (if it does not exist) tenant and it needs to create (if it does not exist) tenant's admin user access_token secret. In the scenario where tenant is already created, but admin access token secret needs to be created, currently there is no way to get a valid access token for that admin user. Available credentials are: Global 3scale master `access_token` and admin's `user/pass`. 3scale API does not allow a way to create/fetch access token for that tenant's admin user. Issue opened on Porta https://github.com/3scale/porta/issues/582

When 3scale API allows getting/creating access_token for that admin user, it needs to be implemented in tenant's controller workflow for the scenario: tenant was already created and admin access token secret does not exist.

**Comment by mikz** [comment]
Why the automation can't just use the impersonation and continue as 3scaleadmin user?  We already provide one extra user for automation on each tenant.

**Comment by eguzki** [comment]
https://github.com/3scale/porta/issues/582#issuecomment-460581709

**Comment by eguzki** [comment]
Will be implemented getting tenant's 'provider_key` from app

closing the issue
