### ISSUE TITLE
Why does the image tag use a different version than the release version?

### ISSUE THREAD

**Issue by grdryn** [3scale/3scale-operator#297]
i.e. for release 0.4.0 of this project, why is the image tag 1.10-4? Is there an advantage to having them be different like this?

**Comment by eguzki** [comment]
image tag 1.10-4 is associated to the latest productized image tag. 

Latest community tag is 0.4.0

**Comment by grdryn** [comment]
@eguzki thanks for the quick reply! :+1: 

I think I understand a little better now. You've got different branches for releasing the community operator and the productized one, right?

I'm still a little confused though:

- Git tag: `v0.4.0`
- CSV: `3scale-community-operator.v0.4.0.clusterserviceversion.yaml`
- Image tag: `v0.4.0`

vs.

- Git tag: `3scale-2.7.0`
- CSV: `3scale-operator.v0.4.0.clusterserviceversion.yaml`
- image tag: `1.10-4`

^ Versioning is consistent in on `v0.4.0` tag, but everything is different on the `3scale-2.7.0` branch (and the v0.4.0 version of the CSV doesn't seem right).

Is this expected to be this way?

**Comment by eguzki** [comment]
That is intended. Though, happy to hear feedback.

We have two packages: productized `3scale-operator` and community `3scale-community-operator`. Each package has one git branch dedicated to store all manifest files. Git tagging is also specific and image tagging is also different. Actually they are not the same docker image, as productized is based on RHEL 7 and community one is based on ubi7. 

CSV tagging has same minor release number, 0.4, but patch release is different currently. Community is still in `0.4.0` while productized one has already been upgraded to `0.4.1`. 

And we also manage the internal` operator [version](https://github.com/3scale/3scale-operator/blob/2.7-stable/version/version.go),  `0.4.0` for CSV 0.4.X z-stream family. That internal operator version is the upgrade mechanism trigger. The operator will not upgrade the product (a.k.a. operand) if that version number does not change. 

As I said, this is quite a madness and happy to hear feedback to simplify this version and release matrix.

**Comment by grdryn** [comment]
@eguzki thanks for the explanation. I don't have any suggestions to improve it, but I'm grateful that I now have an explanation that I can come back to if I'm wondering about this again in a few months! :slightly_smiling_face:
