### ISSUE TITLE
Rename Binding CR

### ISSUE THREAD

**Issue by jmprusi** [3scale/3scale-operator#30]
The name "binding" shouldn't be used as it clashes with other resources.

**Comment by jmprusi** [comment]
@thomasmaas I need some help finding a better name for this object! :)

**Comment by eguzki** [comment]
[3scaleRemotes](https://github.com/3scale/3scale_toolbox/blob/master/docs/remotes.md)

**Comment by miguelsorianod** [comment]
The Binding resource does not exist anymore after changes on the Capabilities functionality. Closing issue.
