### ISSUE TITLE
PVC too small in eval template for cloud deployment

### ISSUE THREAD

**Issue by gsaslis** [3scale/3scale-operator#300]
The RWX PersistentVolumeClaim in the eval template is currently set to `100Mi`. 

While the right choice for local deployment, it's a bit of a problem when trying to deploy the template on a cloud provider where the minimum size may be 1 gb (e.g. see [AWS EBS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html) )

Do you think we could change it to 1 gb by default ?

**Comment by andrewdavidmackenzie** [comment]
Requesting a PV _too small_ causes the deployment to fail???
(wow)

This must be related to EBS only no, as we've been deploying this on AWS (PVC backed by something else...) for a long time now.

Any other workaround that doesn't affect the minimum requested for all other deployments and customers (when not needed)?

**Comment by miguelsorianod** [comment]
Hi,

In a 3scale deployment, RWX PersistentVolumeClaim should be deployed in a RWX-compatible storage. EBS is not a RWX-compatible storage:
https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/storage.html#pv-access-modes

**Comment by gsaslis** [comment]
good point - I guess it would be EFS on AWS and I don't think that has limits in terms of size (since you never define size AFAIK). As such, it wouldn't _fail_ on AWS EFS.

**Comment by eguzki** [comment]
Closing issue. Feel free to reopen if issue is found
