### ISSUE TITLE
Update the operator-sdk version to the latest one

### ISSUE THREAD

**Issue by wei-lee** [3scale/3scale-operator#301]
Hi,

Currently the 3scale-operator is using operator-sdk v0.8.0. Since then there have a few new releases of the operator-sdk, and a bunch of new features and bug fixes are introduced.

There is one particular new feature we (Integreatly) would like to use: [get the metrics for each custom resource](https://github.com/operator-framework/operator-sdk/pull/1277/files). 

However, this means we need to upgrade the version of the operator-sdk for 3scale-operator. We have done this already for some other operators and we would like help to do the same for 3scale.

If I can get agreement that this is something we want to have for 3scale-operator, I can start working on this and create a PR once it's ready.

Thanks.

**Comment by eguzki** [comment]
PR's more than welcome! ;)

**Comment by wei-lee** [comment]
Thanks @eguzki. Will get one created soon!

**Comment by miguelsorianod** [comment]
Done in https://github.com/3scale/3scale-operator/pull/331
