### ISSUE TITLE
Add PodDisruptionBudget when HA is enabled

### ISSUE THREAD

**Issue by wei-lee** [3scale/3scale-operator#303]
## Why?

When 3scale is deployed in HA mode, if the underline k8s or OpenShift is being upgraded, depending how the upgrade is done, there is a chance that all replicas of 3scale deployments will be evicted from current node and move to a new node. This will cause downtime. 

[PodDisruptionBudget](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) is a feature provided by K8S to help solve this problem. It can help limit the number of pod that are down simultaneously. However, it will not work if there is only 1 replica deployed.

## How?

1. When HA mode is enabled, the operator will automatically create corresponding PDB objects for all the deployments that have more than 1 replica.
2. We also need to watch the ReplicaSets and if a deployment is scaled down to 1, we will have to delete the PDB automatically to prevent any possible problems, and create the PDB again if it's scaled up.

We are happy to help progress the work. Would appreciate some thoughts and feedbacks before we get started.

Thanks.

**Comment by andrewdavidmackenzie** [comment]
Question - is there a down-side to specifying the PDB always, even when a pod does not have more than one replica, or when not in HA mode? That would make the Operator logic simpler.

**Comment by wei-lee** [comment]
@andrewdavidmackenzie good question. There might be one: if there is only one replica, and the PDB is set to something like `maxUnavailable=1` (or `minAvailable=1`), then when a node is being drained, the PDB will block the draining process and that might cause issue depending on how the node drain process is performed.

**Comment by wei-lee** [comment]
I should also mention that for now, this work only covers for the components that can be scaled, and won't cover for data stores (like postgres or redis).

**Comment by wei-lee** [comment]
PR sent for this issue: https://github.com/3scale/3scale-operator/pull/308
