### ISSUE TITLE
Cannot Specify Route Certificates

### ISSUE THREAD

**Issue by mathianasj** [3scale/3scale-operator#365]
My OpenShift install does not have a wildcard cert defined, and I need the ability to setup custom certificates for each of the routes.  There is no way to do this currently and the operator resets any changes I make to the routes.

**Comment by eguzki** [comment]
The operator only creates one route, the backend listener route. 

```
https://backend-<tenantName>.<wildcardDomain>
```

Besides, if you changed this route, the operator would not "reset" becase it is configured to not reconcile, just create if it does not exist.

One of the 3scale components, `zync` or `zync-que` is the one responsible to create and maintain those routes.  Open issue in the zync repo: https://github.com/3scale/zync

**Comment by mathianasj** [comment]
So does that mean the routes such as 3scale-admin.xxx are created by zync?  Wouldn’t the default tenant route config still need to be a part of the operator?

**Comment by mathianasj** [comment]
Or are you saying zync needs to support this before for example the tenant crd gets updated to add those options?

**Comment by eguzki** [comment]
The default tenant route config is managed by Zync. If it should be managed by the operator or not is another discussion. I would be happy to have this discussion, but this is not the right place. Currently, it is Zync the one creating and maintaining the routes.

If you want to add certificates to specific routes, zync or 3scale UI should provide this feature. Open issue in the provided GH repo. 

I think they will start recommending installing cluster wide wilcard cert for `*.apps.your-domaind.com`
