### ISSUE TITLE
Provide an option to deploy 3scale using ephemeral storage (empty dir)

### ISSUE THREAD

**Issue by luszczynski** [3scale/3scale-operator#413]
I couldn't find anything in the `APIManager` CR [1] that allows me to deploy 3Scale using ephemeral storage (emptyDir). This is useful for quick demo and demonstrations.
Is it possible?

[1] https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md

**Comment by briangallagher** [comment]
You can provision 3scale with on cluster DBs/Redis, this should be sufficient for demos etc.

**Comment by andrewdavidmackenzie** [comment]
Apart from DB and Redis, there is a need for _either_ a PersistentVolume for static files for the CMS...or an alternative config option to store them on an S3-API-Compatible storage.

Maybe the second option could reduce your requirements for storage for demo purposes @luszczynski ?
If you don't have an S3 you can use, then you would have to setup your own (minio, nooba, etc) which might defeat the purpose...?
