### ISSUE TITLE
Improve 3Scale Documentation: OperatorHub

### ISSUE THREAD

**Issue by mrhillsman** [3scale/3scale-operator#450]
When you install the operator from OpenShift, it does not clearly state the prerequisites and install may happen before prerequisites are completed:

Prerequisites

    OpenShift Container Platform 4.1
    Deploying 3scale using the operator first requires that you follow the steps in quickstart guide about Install the 3scale operator
    Some Deployment Configuration Options require OpenShift infraestructure to provide availablity for the following persistent volumes (PV):
        3 RWO (ReadWriteOnce) persistent volumes
        1 RWX (ReadWriteMany) persistent volume

The RWX persistent volume must be configured to be group writable. For a list of persistent volume types that support the required access modes, see the OpenShift documentation

You can see from this screenshot this crucial information is not visible:

![01](https://user-images.githubusercontent.com/3989695/89922121-3788b300-dbc4-11ea-871f-546487bef1c4.png)

**Comment by miguelsorianod** [comment]
Hi @mrhillsman,

Thank you for your message.

You are right that the ReadWriteMany is often a cause of an APIManager custom resource not being deployed correctly.

This prerequisite however is not a prerequisite of the 3scale-operator. The 3scale-operator does not need a ReadWriteMany volume to be able to work properly. That prerequisite is a prerequisite of the installation of an APIManager, one of the multiple custom resources that the 3scale-operator provides, not of the 3scale-operator itself.

One of the options I can think of might be to reword the 'Documentation' section to something like:

{code}
Documentation can be found on our website[link]:

Please make sure you read the prerequisites on the install guides in order for the custom resources to be deployed with their required prerequisites
{code}

What do you think?

**Comment by mrhillsman** [comment]
@miguelsorianod sorry for being so late on the response, bug referencing this issue was not in immediate view. I think the change you suggest works.
