### ISSUE TITLE
[system] Add PROMETHEUS_EXPORTER_PORT environment

### ISSUE THREAD

**Issue by hallelujah** [3scale/3scale-operator#453]
We are adding more prometheus exporter endpoint to System component.

- system-app
- system-sidekiq

Each container of each pod should have different `PROMETHEUS_EXPORTER_PORT` value

Container | Port | Service
---------------|---------|-----
system-master |  9394 | web server
system-provider |  9395 | web server
system-developer |  9396 | web server
system-sidekiq | 9394 | sidekiq

The endpoint are accessible from `http://{server}:{port}/metrics` where `server` is normally `0.0.0.0` locally

**Comment by eguzki** [comment]
For SystemApp pods containers, just let us know the port numbers and we will configure make all the arrangements to have prometheus scraping metrics. 

For systemSidekiq, Currently there are exposed metrics at port 9394 https://github.com/3scale/3scale-operator/blob/df0c0e962f5fd42926d52d316090d574e2ba4ae5/pkg/3scale/amp/component/system.go#L99 If you change it or add a new metric service, let us know the port number to do all the integration with the prometheus.

**Comment by hallelujah** [comment]
@eguzki I updated the table, you can take them as the reference

**Comment by miguelsorianod** [comment]
Hi @hallelujah,

When you say `Each container of each pod should have different PROMETHEUS_EXPORTER_PORT value` do you mean we should set/send the environment variable `PROMETHEUS_EXPORTER_PORT` to the container?

**Comment by miguelsorianod** [comment]
What are the endpoints for the metrics in the system-app containers? `/metrics` ?

**Comment by miguelsorianod** [comment]
@hallelujah,

As @eguzki said, For system-sidekiq we are already using SystemSidekiqMetricsPort = 9394
Can you make that the default for Sidekiq in system code?

**Comment by hallelujah** [comment]
Closing as those port are defaults if the environment variable is not set see https://github.com/3scale/porta/pull/2093
