### ISSUE TITLE
Add SOPs/runbooks for all Prometheus critical alerts

### ISSUE THREAD

**Issue by obrienrobert** [3scale/3scale-operator#464]
Enabling monitoring in 2.9 adds a number of new Prometheus alerts, many of which are of critical severity. Before we (the RHMI team) can enable monitoring, we have to ensure that these critical alerts meet the acceptance criteria outlined by CS-SRE, one of which states that all critical alerts must have an accompanying SOP/run-book (linked via an annotation in the alert) that includes detailed steps on how to resolve/investigate the alert.

We have many examples of SOP's that were created for the critical alerts within RHMI. If needed, these could be shared to show the kind of detail each one contains, and how they are structured.

**Comment by obrienrobert** [comment]
@miguelsorianod

**Comment by thomasmaas** [comment]
@obrienrobert Lets discuss in our API Management Service - PM/ENG Sync. Call this Wednesday. And then subsequently create a Jira.

**Comment by austincunningham** [comment]
Closing this as RHMI has its own SOP's for SRE.
