### ISSUE TITLE
System-app pod stopped suddenly

### ISSUE THREAD

**Issue by Ajay2307** [3scale/3scale-operator#508]
Hey there,

System-app pod stopped suddenly. 

Below are the logs of **system-app** pod after rolling out the DeploymentConfig **system-app**. 

`[root@helper ~]# oc logs -f system-app-8-deploy 
--> pre: Running hook pod ...
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/bundler-1.17.3/lib/bundler/runtime.rb:81)
DEPRECATION WARNING: `config.static_cache_control` is deprecated and will be removed in Rails 5.1.
Please use
`config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=31557600' }`
instead.
 (called from block in <top (required)> at /opt/system/config/environments/production.rb:117)
I, [2020-10-29T09:47:47.285861 #1]  INFO -- : ActiveMerchant MODE set to 'production'
W, [2020-10-29T09:47:47.414729 #1]  WARN -- [Bugsnag]: No valid API key has been set, notifications will not be sent
I, [2020-10-29T09:47:48.187134 #1]  INFO -- : [Core] Using http://backend-listener:3000/internal/ as URL
OpenIdAuthentication.store is nil. Using in-memory store.`

Rest all pods are up and running.

Can I please have a solution for this issue?

**Comment by miguelsorianod** [comment]
Hi @Ajay2307,

None of those logs seem to suggest any issue. They are expected.

More information is needed to find the cause of the issue.

How is 3scale being deployed? what version?
Do the operator logs show any issue?
Do you see any errors in the events (`oc get events`)?
Do you see any errors in the system-app DC / pod (`oc describe dc system-app, oc describe pod <mysystempod>)?

**Comment by briangallagher** [comment]
Closing, no response sine Oct 2020
