### ISSUE TITLE
A way to throttle requests to quay.io? Hitting rate limits

### ISSUE THREAD

**Issue by cloudbustinguk** [3scale/3scale-operator#583]
Hi,

When deploying the operator and creating an `APIManager` instance, we're hitting:

```
2.7 (latest)
  tagged from quay.io/3scale/3scale27:zync-3scale-2.7.0-GA

  ! error: Import failed (InternalError): Internal error occurred: quay.io/3scale/3scale27:zync-3scale-2.7.0-GA: Get "https://quay.io/v2/3scale/3scale27/manifests/zync-3scale-2.7.0-GA": error parsing HTTP 429 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>429 Too Many Requests</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>429 Too Many Requests</h1></center>\r\n<hr><center>nginx/1.12.1</center>\r\n</body>\r\n</html>\r\n"
      15 seconds ago
```

Ironically, out of the ~9 images which our particular deployment pulls, it's always one which fails (not always the same individual image, though; simply 1/9 fails).

The quay.io rate limiting threshold seems a bit low.

Would you be open to a PR to throttle the image reconciler?

Has anyone else encountered this?

Cheers

**Comment by eguzki** [comment]
I do not think the operator can do anything about this. The operator declares the images required for the deployment, which can be from several image repositories, not only quay.io. That is all from the operator perspective, declare the images. It is the imagestream controller who fetches the images to the internal registry. 

AFAIK there is no mechanism to throttle requests to quay.io from the [imagestream OCP resource](https://docs.openshift.com/container-platform/4.6/openshift_images/image-streams-manage.html)

Maybe the solution is using some premium account? The operator allows setting [your own service account image pull secret](https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md#apimanagerspec) with the attribute `.spec.imagePullSecrets`

**Comment by cloudbustinguk** [comment]
Hi Eguzki,

Thanks for your reply. I have re-worked our deployment script to simply `podman pull ...` in serial fashion, and thereby also cache locally. It seems to be the only way to circumvent this limit, other than your suggestion of paying for a premium account.

Many thanks
