### ISSUE TITLE
Consider increasing memory limits for backend-cron

### ISSUE THREAD

**Issue by davidor** [3scale/3scale-operator#584]
After updating the backend image to use Ruby 2.7 and be based on UBI8, we noticed that the backend-cron pod was being OOM killed because just after creating it, it was consuming ~100MB, which exceeds its current limits.

To fix this we simply raised the limit to 150MB. The new image will be used in 3scale 2.11, so no need to change this for 2.10.

Ref: https://github.com/3scale/saas-operator/pull/81

**Comment by miguelsorianod** [comment]
As a note for our future selves:
If we go for this approach an upgrade procedure for when `resourceRequirementsEnabled` is set to `true` and the user has not explicitly set resource requirements at backend-cron level will be needed.
