### ISSUE TITLE
backend-cron config map

### ISSUE THREAD

**Issue by Gift-23** [3scale/3scale-operator#609]
Hi,

i'm trying to deploy a 3scale api manager using the operator on Openshift 4.7, all containers are running besides for the backend-cron container. the config map of the backend-cron didn't get created.

the below config maps got created:

1. 3scale-operator-lock 
2. kube-root-ca.crt 
3. mysql-extra-conf
4. mysql-main-conf
5. redis-config

please assist

**Comment by eguzki** [comment]
Depends on the deployment mode (local persistence vs S3 or external databases or embedded databases) but a usual 3scale deployments have these config maps being deployed:
```
$ cat amp.yml | yq eval '.objects[] | select(.kind == "ConfigMap") | .metadata.name' -
redis-config
backend-environment
mysql-main-conf
mysql-extra-conf
system
system-environment
apicast-environment
```

If some of those have not been deployed, means that the operator is failing at some point and cannot continue. Can you please check operator logs and namespace events? The real issue may be shown.

**Comment by briangallagher** [comment]
Closing, no response sine May 2021
