### ISSUE TITLE
APIManagerStatus condition never reports Available=True

### ISSUE THREAD

**Issue by seanuleh** [3scale/3scale-operator#689]
**Environment**
- OpenShift v4.9.0
- 3scale operator v0.8.0-0.1634606167.p

When using the operator to deploy my cluster, all cluster components come up successfully, however, the APIManagerStatus condition for 'Available' never reports 'True'.

[APIManagerStatus documentation](https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md#apimanagerstatus) states that the status should report available when:

- All expected DeploymentConfigs to be deployed exist and have the `Available` condition set to true
- All 3scale default OpenShift routes exist and have the Admitted condition set to true. The default routes are:
  - Master route
  - Backend Listener route
  - Default tenant admin route, developer route, APIcast staging and production routes beloinging to the default tenant

      
All the above are true in my environment, however the available condition does not update from 'False'

**Comment by briangallagher** [comment]
@seanuleh This should be working now. Please reopen another issue if still relevant
