### ISSUE TITLE
Feature Request: Application Creation via Operator

### ISSUE THREAD

**Issue by bthdimension** [3scale/3scale-operator#702]
Currently, the operator offers 3Scale Backends and 3Scale Products (among others). However, there is no CRD for 3Scale Applications. 

The Application should be created in 3Scale by the operator when a CR of kind "Application" was created. The operator should also update the Application based on changes and delete the Application in 3Scale when the CR was deleted.

Ideally, the following fields could be provided:
- Application Name
- Account
- Description
- Service (Product)
- Application Plan
- State
- API Credentials (user_key)

**Comment by eguzki** [comment]
Jira issue is already created https://issues.redhat.com/browse/THREESCALE-7668

**Comment by bthdimension** [comment]
Great, thanks for the quick reply :-) Do you already know when this feature will be implemented and released?

**Comment by eguzki** [comment]
It is expected to be in the 3scale  2.12 release

**Comment by briangallagher** [comment]
JIRA complete
