### ISSUE TITLE
Products/Backends are not deleted when the CR is deleted

### ISSUE THREAD

**Issue by bthdimension** [3scale/3scale-operator#704]
When a Products/Backend CR is created/updated in OpenShift, the operator creates/updates the Product/Backend on 3Scale. However, when a CR is deleted, the operator does not delete the respective Product or Backend in 3Scale.

**Comment by eguzki** [comment]
Reconcile deleting Backend CR: https://issues.redhat.com/browse/THREESCALE-6580
Reconcile deleting Product CR: https://issues.redhat.com/browse/THREESCALE-6581

**Comment by eguzki** [comment]
Implemented
