### ISSUE TITLE
Cannot sync in ArgoCD to Openshift 4 with replicas in sphinxSpec 

### ISSUE THREAD

**Issue by ghijsma** [3scale/3scale-operator#787]
Using:
- Openshift 4.10 (k8s v1.23.5+8471591)
- ArgoCD v2.3.7+unknown
- 3scale-operator.v0.9.1
- 3Scale API GW v3.12

When adding replicas under spec.apicast.system.sphinxSpec our ArgoCD throws an exeption on syncing. 

```apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
...
spec:
...
  apicast:
   ...
  backend:
    ...
  system:
    ...
    sidekiqSpec:
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 750Mi
        requests:
          cpu: 100m
          memory: 512Mi
    sphinxSpec:
      replicas: 1
      resources:
        limits:
          cpu: 750m
          memory: 750Mi
        requests:
          cpu: 50m
          memory: 600Mi
```

`error validating data: ValidationError(APIManager.spec.system.sphinxSpec): unknown field "replicas" in net.3scale.apps.v1alpha1.APIManager.spec.system.sphinxSpec`

The other components seem to work fine with adding replicas. Also, adding replica's manually in Openshift seems to work fine. Can someone please look into this?

**Comment by ghijsma** [comment]
Looks like there is this one piece missing in system_reconciler_test.go that is not missing for the other components, Could it be that this is the culprit? 
https://github.com/3scale/3scale-operator/blob/ca185cb2b8addafee52dd0d55c4927c028cc048f/pkg/3scale/amp/operator/system_reconciler_test.go

240 - `SphinxSpec:      &appsv1alpha1.SystemSphinxSpec{},`

239 - `SidekiqSpec:     &appsv1alpha1.SystemSidekiqSpec{Replicas: sidekiqReplicas},`

**Comment by eguzki** [comment]
[SphinxSpec](https://github.com/3scale/3scale-operator/blob/master/doc/apimanager-reference.md#SystemSphinxSpec) does not have `replicas` field defined. That is why OCP complains with some `unknown field "replicas"`.

Does it make sense to add replicas to the sphinx component?

**Comment by ghijsma** [comment]
Seems the issue is solved by setting the database privileges right.
