### ISSUE TITLE
Guidelines to configure vCPU/RAM based API calls

### ISSUE THREAD

**Issue by lionelmace** [3scale/3scale-operator#801]
Is there somewhere some guidelines to configure correctly the amount of vCPU/RAM based on the number of API calls?

**Comment by thomasmaas** [comment]
Hi @lionelmace, there is the doc that contains [the default values](https://github.com/3scale/3scale-operator/blob/3scale-2.13-stable/doc/apimanager-reference.md#default-apimanager-components-compute-resources) but that won't really answer your question on scaling other than "you have to perform your own tests and measurements for your specific workload". Anything more substantial we can offer @3scale/support ?

**Comment by kevprice83** [comment]
@lionelmace we don't advise scaling vertically to process more API traffic. Our recommendation is always to scale horizontally and leave the default `requests` & `limits` as they are. Is there any reason specifically you are looking to modify the resources instead of replicas?

**Comment by lionelmace** [comment]
I found what I was looking for in the table `Resource Requirements` in this article
https://access.redhat.com/articles/5534341
