### ISSUE TITLE
Condition spec for proxy promotes has wrong doc

### ISSUE THREAD

**Issue by mkudlej** [3scale/3scale-operator#878]
It seems to me that https://github.com/3scale/3scale-operator/blame/1db6421d27a2af3815da0a304d73966deb535211/doc/proxyConfigPromote-reference.md#L77 is not changed according https://github.com/3scale/3scale-operator/pull/863 and it contains reference to ActiveDoc doc.

**Comment by austincunningham** [comment]
@MStokluska looks like we need to update the proxyConfigPromote docs to aline with #863

**Comment by MStokluska** [comment]
https://github.com/3scale/3scale-operator/pull/879
