### ISSUE TITLE
add OAuth2/OIDC to supported sec. schemes in OpenAPI limitations

### ISSUE THREAD

**Issue by mkudlej** [3scale/3scale-operator#886]
I think $subj should be added to https://github.com/3scale/3scale-operator/blob/master/doc/openapi-user-guide.md#supported-openapi-spec-version-and-limitations because of https://github.com/3scale/3scale-operator/pull/837

**Comment by MStokluska** [comment]
Resolved with https://github.com/3scale/3scale-operator/pull/887
