### ISSUE TITLE
3Scale dashboard are not reachable

### ISSUE THREAD

**Issue by jdchdev** [3scale/3scale-operator#896]
I've installed latest Rad Hat Integration - 3Scale Operator on ARO 4 and created the ApiManager but when I try to access to the dashboard through routes these pages are not accessible.

I left some pictures to give you more context.
![redhat_openshift_img](https://github.com/3scale/3scale-operator/assets/11200278/833d981c-3703-401e-8340-bf9586fb1b2b)
![redhat_openshift_img_2](https://github.com/3scale/3scale-operator/assets/11200278/604d151a-2f35-4f9d-8766-f8579e4b9fce)
What am I doing wrong?

I hope you have the solution.

**Comment by austincunningham** [comment]
@jdchdev I suspect (screen shots suggest this) that you used `example.com` for the wildcard domain in the APIManager CR . This domain needs to be resolvable on your cluster.   For you to be able to use this domain you would need to own the domain and set it up as a [custom domain](https://docs.openshift.com/rosa/applications/deployments/osd-config-custom-domains-applications.html) on your cluster. 

Alternative you could just use the Openshift default application router as the wild card domain. This command should give it to you
```bash
// need jq to run this command  https://jqlang.github.io/jq/
oc get routes console -n openshift-console -o json | jq -r '.status.ingress[0].routerCanonicalHostname' | sed 's/router-default.//'
```
Openshift default application router can also be got from your Openshift console route just remove the `console-openshift-console` part of the route e.g. 

This 
console-openshift-console.**apps.aucunnin.4mog.s1.devshift.org**

To this
apps.aucunnin.4mog.s1.devshift.org

**Comment by jdchdev** [comment]
@austincunningham I tried it using canonical hostname
![image](https://github.com/3scale/3scale-operator/assets/11200278/f95b57c0-54af-41a3-a859-e8e4d6c9461c)

the pods are running ok.

**Comment by jdchdev** [comment]
@austincunningham  thank you, I created a new API manager this time with cluster domains and looks good now
