### ISSUE TITLE
If there are more than one Plan set as default causes the state to be always out of sync

### ISSUE THREAD

**Issue by jmprusi** [3scale/3scale-operator#97]
If there are multiple plans with "default" set to true, the state will never be in sync.

**Comment by miguelsorianod** [comment]
@eguzki is this still an issue with the new implementation?

**Comment by eguzki** [comment]
The new implementation does not implement any option to define the default plan of a product. 

I would implement at product level to avoid this issue. Only one plan can be the default one. Internal reference should be validated (default plan ref is one of the listed plans)
